function processedFrame = processOneFrame(idx,ePerFrameCumsum,ePerFrameList,...
                                          x_data,y_data,pol_data,t_data,...
                                          retinaRes,dEROS,kEROS,sR,...
                                          method,prevProcessedFrame,...
                                          gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent,kEVENT,setEventTilt,mEVENT,eventType,clipLevel)

    %Be very careful here! It keeps track of the correct events sent
    %for processing!!!
    iend = ePerFrameCumsum(idx);
    eNr = ePerFrameList(idx);
    istart = iend-eNr+1;

    %convert coordinate data to int32 only for the c-code then! so that c can handle it better
    x_data_uint16 = x_data(istart:iend);
    y_data_uint16 = y_data(istart:iend);
    pol_data_uint16 = pol_data(istart:iend);

    %x_data_double = double(x_data_uint16);
    %y_data_double = double(y_data_uint16);

    %uncomment this when using the app! this is just for testing!
   % method = 'override';

    switch method
        case 'EROS'
            processedFrame = EROS_all_double(prevProcessedFrame,x_data_uint16,...
                             y_data_uint16,pol_data_uint16,...
                             retinaRes,kEROS,dEROS,eNr);

        case 'EROS_slim' 
            processedFrame = EROS_all_double_slim(prevProcessedFrame,x_data_uint16,...
                             y_data_uint16,...
                             kEROS,dEROS);

        case 'EROS_slim_mex' 
            processedFrame = EROS_all_double_slim_mex(prevProcessedFrame,x_data_uint16,...
                             y_data_uint16,...
                             kEROS,dEROS);

        case 'LAPLACE'
            processedFrame = EROS_all_double_laplace(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,pol_data_uint16,...
                         retinaRes,kEROS,dEROS,sR,eNr);

        case 'GAUSS'
            processedFrame = EROS_all_double_gauss(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,hGAUSS,kGAUSS,r0,sGAUSS);
        case 'GAUSS_mex'
            processedFrame = EROS_all_double_gauss_mex(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,hGAUSS,kGAUSS,r0,sGAUSS);
        
        case 'ASYMP'
            processedFrame = EROS_all_double_asymp(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS);
        case 'ASYMP_mex'
            processedFrame = EROS_all_double_asymp_mex(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS);

        case 'ENHANCE_mex'
            processedFrame = EROS_all_double_enhance_mex(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS);

        case 'ENHANCE_XTRA'
            processedFrame = EROS_all_double_enhance_xtra(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent);

        case 'ENHANCE_XTRA_mex'
            processedFrame = EROS_all_double_enhance_xtra_mex(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent);

        case 'SET_KERNEL'
            processedFrame = EROS_all_double_setKernel(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent,kEVENT,setEventTilt);

        case 'SET_KERNEL_mex'
            processedFrame = EROS_all_double_setKernel_mex(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent,kEVENT,setEventTilt);

        case 'SET_KERNEL_3_mex'
            processedFrame = EROS_all_double_setKernel_3_mex(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent,kEVENT,setEventTilt,mEVENT);

        case 'SET_ADD_KERNEL_max_5'
            processedFrame = EROS_all_double_setaddKernel_limit5(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent,kEVENT,setEventTilt,mEVENT,eventType);

        case 'SET_ADD_KERNEL_max_5_mex'
            processedFrame = EROS_all_double_setaddKernel_limit5_mex(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent,kEVENT,setEventTilt,mEVENT,eventType);

        case 'SET_ADD_MULT_KERNEL_max_5_mex'
            processedFrame = EROS_all_double_set_add_mult_Kernel_limit5_mex(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent,kEVENT,setEventTilt,mEVENT,eventType);

        case 'SET_ADD_CLIP1_max_5'
            processedFrame = EROS_all_double_set_add_clip1_limit5(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent,kEVENT,setEventTilt,mEVENT,eventType);

        case 'SET_ADD_CLIP1_max_5_mex'
            processedFrame = EROS_all_double_set_add_clip1_limit5_mex(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent,kEVENT,setEventTilt,mEVENT,eventType);

        case 'SET_ADD_CLIP_ANY_max_5'
            processedFrame = EROS_all_double_set_add_clipAny_limit5(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent,kEVENT,setEventTilt,mEVENT,eventType,clipLevel);    

        case 'SET_ADD_CLIP_ANY_max_5_mex'
            processedFrame = EROS_all_double_set_add_clipAny_limit5_mex(prevProcessedFrame,x_data_uint16,...
                         y_data_uint16,...
                         kEROS,gGAUSS,hGAUSS,kGAUSS,r0,sGAUSS,setEvent,kEVENT,setEventTilt,mEVENT,eventType,clipLevel);


        case 'cEROS'
            %do something
        otherwise
            error('Unknown processing method: %s', method);
    end


    
end